# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '22.x'
  displayName: 'Use Node.js'

- script: npm ci
  displayName: 'Install dependencies'

- script: ng run build -- --configuration=production
  displayName: 'Build Angular app'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/frontDelivery'
    ArtifactName: 'drop'
    publishLocation: 'Container'

